# Be-Mobile API
Move smarter together with the Be-Mobile API.

## Audience
      
This document is intended for website and mobile developers who want to compute direction data within maps provided by the Be-Mobile API. It provides an introduction to using the API and reference material on the available parameters.
      
## API Key
      
> **Note**: Business users must include `client` and `signature` parameters with their requests instead of a key.
     
All Be-Mobile API applications should use an API key. Including a key in your request:

* Allows you to monitor your application's API usage in the APIs Console.
* Enables per-key instead of per-IP-address quota limits.
* Ensures that Be-Mobile can contact you about your application if necessary.
 
The Directions API uses an API key to identify your application. API keys are managed through the [Be-Mobile API console](https://developers.be-mobile-international.com/api/console). To create your key:

1. Visit the API console at https://developers.be-mobile-international.com/api/console and log in with your Be-Mobile Account.
2. Click the **Services** link from the left-hand menu in the APIs Console, then activate the **Directions API** service.
3. Once the service has been activated, your API key is available from the **API Access** page, in the **Simple API Access** section. Directions API applications use the Key for server apps.

To specify a key in your request, include it as the value of a key parameter.

> **Note**: By default, a key can be used from any server. We strongly recommend that you restrict the use of your key by IP address to servers that you administer. You can specify which IP addresses are allowed to use your API key by clicking the **Edit allowed referers...** link in the API console. HTTPS is enforced for requests that include an API key.

## XML versus JSON

We recommend that you use json as the preferred output flag unless your service requires xml for some reason. Processing XML trees requires some care, so that you reference proper nodes and elements. JSON is lighter, faster and easier to read (both by people and machines).

> The remainder of this documentation will use JSON syntax. In most cases, the output format does not matter for purposes of illustrating concepts or field names in the documentation. However, note that blank elements are indicated through empty arrays in JSON, but by the absence of any such element in XML.

# Group Routeplanner
## Functional description
      
The `routeplanner` endpoint is a service that calculates directions between locations using an HTTP request. You can search for directions for several modes of transportation, include public transport, driving, walking or cycling. 
      
Directions may specify origins, destinations and waypoints either as text strings or as latitude/longitude coordinates. The Routeplanner API can return multi-part directions using a series of waypoints.
      
### Travel Modes

When you calculate directions, you may specify which transportation `mode` to use. By default, directions are calculated as `car` directions. The following travel modes are currently supported:

* `car` (default) indicates standard driving directions using the road network.
* `foot` requests walking directions via pedestrian paths & sidewalks (where available).
* `bicycle` requests bicycling directions via bicycle paths & preferred streets (where available).
* `public_transport` requests directions via public transport (where available).

### Using Waypoints

When calculating routes using the Routeplanner endpoint, you may also specify waypoints for driving, walking or bicycling directions. Waypoints allow you to calculate routes through additional locations, in which case the returned route passes through the given waypoints.

Waypoints are specified within the waypoints parameter and consist of one or more addresses or locations separated by the pipe (|) character.

### Travelling Salesman

By default, the Routeplanner service calculates a route through the provided waypoints in their given order. Optionally, you may pass `optimize:true` as the first argument within the waypoints parameter to allow the Routeplanner service to optimize the provided route by rearranging the waypoints in a more efficient order. This optimization is an application of the [Travelling Salesman Problem](http://en.wikipedia.org/wiki/Travelling_salesman_problem).

If you instruct the Routeplanner service to optimize the order of its waypoints, their order will be returned in the `waypoint_order` field within the routes object. The `waypoint_order` field returns values which are zero-based.

### Avoiding

Directions may be calculated that adhere to certain restrictions. Restrictions are indicated by use of the `avoid` parameter, and an argument to that parameter indicating the restriction to avoid. The following restrictions are supported:

* `tolls`
* `highways`
* `ferries`

It's possible to request a route that avoids any combination of tolls, highways and ferries.

## Technical Description

### Usage Limits

This service is generally designed for calculating directions for static (known in advance) addresses for placement of application content on a map; this service is **not** designed to respond in real time to user input, for example.

Route planning is a time and resource intensive task. Whenever possible, calculate known addresses ahead of time (using the service described here) and store your results in a temporary cache of your own design.

The Routeplanner API has the following limits in place:

Users of the free API:

* 2,500 requests per 24 hour period.
* Up to 8 waypoints allowed in each request.
* 10 requests per second.

Business Users:

* 100,000 requests per 24 hour period.
* 23 waypoints allowed in each request.
* 10 requests per second.

Routeplanner API URLs are restricted to approximately 2000 characters, after URL Encoding. As some Routeplanner API URLs may involve many locations along a path, be aware of this limit when constructing your URLs.

### Region Biasing

You can also set the Routeplanner service to return results biased to a particular region by use of the `region` parameter. This parameter takes a ccTLD (country code top-level domain) argument specifying the region bias. Most ccTLD codes are identical to ISO 3166-1 codes, with some notable exceptions. For example, the United Kingdom's ccTLD is "uk" (.co.uk) while its ISO 3166-1 code is "gb" (technically for the entity of "The United Kingdom of Great Britain and Northern Ireland").

An example is 'Amsterdam', a city in The Netherlands, but also in the USA (with no less than 11 Amsterdams), Canada and South-Africa. Region biasing will help select the correct Amsterdam.

Region codes can be concatenated using the pipe symbol (|).

### Routeplanner API Calls [/routeplanner/{format}{?origin,destination,mode,waypoints,alternatives,avoid,region,departure_time,arrival_time,routing_cost,effective_cost,key}]
#### Get directions [GET]
+ Parameters
    + format (required, string, `json`) ... `format` may be either of the following values:    
    
        * `json` (recommended) indicates output in JavaScript Object Notation (JSON)
        * `xml` indicates output as XML
        
    + origin (required, string, `Ghent, Belgium or 51.055|3.715`) ... The address or textual latitude/longitude value from which you wish to calculate directions. If you pass an address as a string, the Routeplanner service will geocode the string and convert it to a latitude/longitude coordinate to calculate directions. If you pass coordinates, ensure that no space exists between the latitude and longitude values.

    + destination (required, string, `Brussels, Belgium or 50.85|4.35`) ... The address or textual latitude/longitude value from which you wish to calculate directions. If you pass an address as a string, the Routeplanner service will geocode the string and convert it to a latitude/longitude coordinate to calculate directions. If you pass coordinates, ensure that no space exists between the latitude and longitude values.
    
    + mode (optional, string, `bicycle|public_transport`) ... Specifies the mode of transport to use when calculating directions. Values can be pipe-concatenated. Valid values are:
        
        * `foot`
        * `bicycle`
        * `public_transport`
        * `car`
        
    + waypoints (optional, string, `St.-Niklaas|Lokeren`) ... Specifies an array of waypoints. Waypoints alter a route by routing it through the specified location(s). A waypoint is specified as either a latitude/longitude coordinate or as an address which will be geocoded. (For more information on waypoints, see Using Waypoints and Travelling Salesman)
    
    + alternatives (optional, integer, `3`) ... Specifies the number of route alternatives the Routeplanner service may provide. Note that providing route alternatives may increase the response time from the server.
    
    + avoid (optional, string, `toll|highways`) ... Indicates that the calculated route(s) should avoid the indicated features. This parameter supports the following arguments. 
        
        * `tolls` indicates that the calculated route should avoid toll roads/bridges. 
        * `highways` indicates that the calculated route should avoid highways. 
        * `ferries` indicates that the calculated route should avoid ferries.
    
    + region (optional, string, `be`) ... The region code, specified as a ccTLD ("top-level domain") two-character value. (For more information see Region Biasing)
    
    + departure_time (optional, string, `2014-10-22T09:00:00Z`) ... Specifies the desired time of departure in UTC. Format is `YYYY-MM-DDTHH:mm:ssZ`. `departure_time` and `arrival_time` cannot be specified together.
    
    + arrival_time (optional, string, `2014-10-22T09:00:00Z`) ... Specifies the desired time of arrival in UTC. Format is `YYYY-MM-DDTHH:mm:ssZ`. `departure_time` and `arrival_time` cannot be specified together.
    
    + routing_cost (optional, string, `optimal_speed`) ... Routing cost model. Options are 
    
        * `optimal_speed` 
        * `simple_osm`
        * `realtime`
        * `smart`
        * `optimal_alternative`
        * `realtime_alternative`

    + effective_cost (optional, string, `optimal_speed`) ... Effective cost model. Options are 
    
        * `optimal_speed`
        * `simple_osm`
        * `realtime`
        * `smart`
        
    + key (required, string, `BeMoSyB-A8Y82Lsncu9iUQtR-LUooaitdsexsknI`) ... All Be-Mobile API applications should use an API key.
    
    
+ Response 200 (application/json)

    + Header

    + Body
    
            {
              "status": "OK",
              "routes": [ {
                "summary": "E40 W",
                "legs": [ {
                  "steps": [ {
                    "travel_mode": "car",
                    "start_location": {
                      "lat": 41.8507300,
                      "lng": -87.6512600
                    },
                    "end_location": {
                      "lat": 41.8525800,
                      "lng": -87.6514100
                    },
                    "polyline": {
                      "points": "a~l~Fjk~uOwHJy@P"
                    },
                    "duration": {
                      "value": 19,
                      "text": "1 min"
                    },
                    "html_instructions": "Head \u003cb\u003enorth\u003c/b\u003e on \u003cb\u003eS Morgan St\u003c/b\u003e toward \u003cb\u003eW Cermak Rd\u003c/b\u003e",
                    "distance": {
                      "value": 207,
                      "text": "0.1 mi"
                    }
                  },
                  // ... additional steps of this leg
                //... additional legs of this route
                  "duration": 74384,
                  "distance": 2137146,
                  "start_location": {
                    "lat": 35.4675602,
                    "lng": -97.5164276
                  },
                  "end_location": {
                    "lat": 34.0522342,
                    "lng": -118.2436849
                  },
                  "start_address": "Ghent, Belgium",
                  "end_address": "Brussels, Belgium"
                } ],
                "copyrights": "Route data ©2014 Be-Mobile, Belgium",
                "overview_polyline": {
                  "points": "a~l~Fjk~uOnzh@vlbBtc~@tsE`vnApw{A`dw@~w\\|tNtqf@l{Yd_Fblh@rxo@b}@xxSfytAblk@xxaBeJxlcBb~t@zbh@jc|Bx}C`rv@rw|@rlhA~dVzeo@vrSnc}Axf]fjz@xfFbw~@dz{A~d{A|zOxbrBbdUvpo@`cFp~xBc`Hk@nurDznmFfwMbwz@bbl@lq~@loPpxq@bw_@v|{CbtY~jGqeMb{iF|n\\~mbDzeVh_Wr|Efc\\x`Ij{kE}mAb~uF{cNd}xBjp]fulBiwJpgg@|kHntyArpb@bijCk_Kv~eGyqTj_|@`uV`k|DcsNdwxAott@r}q@_gc@nu`CnvHx`k@dse@j|p@zpiAp|gEicy@`omFvaErfo@igQxnlApqGze~AsyRzrjAb__@ftyB}pIlo_BflmA~yQftNboWzoAlzp@mz`@|}_@fda@jakEitAn{fB_a]lexClshBtmqAdmY_hLxiZd~XtaBndgC"
                },
                "warnings": [ ],
                "waypoint_order": [ 1, 0 ],
                "bounds": {
                  "southwest": {
                    "lat": 34.0523600,
                    "lng": -118.2435600
                  },
                  "northeast": {
                    "lat": 41.8781100,
                    "lng": -87.6297900
                  }
                }
              } ]
            }
